import os

import subprocess

git_branches = \
    {
        'support':
            {
                u'support / shotgun_client_delivery':
                    {
                        'url': u'http://git01.base-fx.com:88/support/shotgun_client_delivery',
                        'clone': 'git clone http://git01.base-fx.com:88/support/shotgun_client_delivery'
                    },
                u'support / services':
                    {
                        'url': u'http://git01.base-fx.com:88/support/services',
                        'clone': 'git clone http://git01.base-fx.com:88/support/services'
                    },
                u'support / executable_template':
                    {
                        'url': u'http://git01.base-fx.com:88/support/executable_template',
                        'clone': 'git clone http://git01.base-fx.com:88/support/executable_template'
                    },
                u'support / shotgun_event_handler': {
                    'url': u'http://git01.base-fx.com:88/support/shotgun_event_handler',
                    'clone': 'git clone http://git01.base-fx.com:88/support/shotgun_event_handler'},
                u'support / shotgun_archive': {'url': u'http://git01.base-fx.com:88/support/shotgun_archive',
                                               'clone': 'git clone http://git01.base-fx.com:88/support/shotgun_archive'},
                u'support / bfx_support': {'url': u'http://git01.base-fx.com:88/support/bfx_support',
                                           'clone': 'git clone http://git01.base-fx.com:88/support/bfx_support'},
                u'support / wrappers': {'url': u'http://git01.base-fx.com:88/support/wrappers',
                                        'clone': 'git clone http://git01.base-fx.com:88/support/wrappers'},
                u'support / bfx_extend_rv': {'url': u'http://git01.base-fx.com:88/support/bfx_extend_rv',
                                             'clone': 'git clone http://git01.base-fx.com:88/support/bfx_extend_rv'},
                u'support / itd_support': {'url': u'http://git01.base-fx.com:88/support/itd_support',
                                           'clone': 'git clone http://git01.base-fx.com:88/support/itd_support'},
                u'support / bfx_admin': {'url': u'http://git01.base-fx.com:88/support/bfx_admin',
                                         'clone': 'git clone http://git01.base-fx.com:88/support/bfx_admin'},
                u'support / ple_util': {'url': u'http://git01.base-fx.com:88/support/ple_util',
                                        'clone': 'git clone http://git01.base-fx.com:88/support/ple_util'},
                u'support / bfx_docker_images': {'url': u'http://git01.base-fx.com:88/support/bfx_docker_images',
                                                 'clone': 'git clone http://git01.base-fx.com:88/support/bfx_docker_images'},
                u'support / bfx_mq': {'url': u'http://git01.base-fx.com:88/support/bfx_mq',
                                      'clone': 'git clone http://git01.base-fx.com:88/support/bfx_mq'},
                u'support / kuaidi': {'url': u'http://git01.base-fx.com:88/support/kuaidi',
                                      'clone': 'git clone http://git01.base-fx.com:88/support/kuaidi'},
                u'support / shotgun_data_validation': {
                    'url': u'http://git01.base-fx.com:88/support/shotgun_data_validation',
                    'clone': 'git clone http://git01.base-fx.com:88/support/shotgun_data_validation'},
                u'support / deploy_studio': {'url': u'http://git01.base-fx.com:88/support/deploy_studio',
                                             'clone': 'git clone http://git01.base-fx.com:88/support/deploy_studio'},
                u'support / bfx_codestandards': {'url': u'http://git01.base-fx.com:88/support/bfx_codestandards',
                                                 'clone': 'git clone http://git01.base-fx.com:88/support/bfx_codestandards'},
                u'support / bfx_init_pipeline': {'url': u'http://git01.base-fx.com:88/support/bfx_init_pipeline',
                                                 'clone': 'git clone http://git01.base-fx.com:88/support/bfx_init_pipeline'},
                u'support / dvd': {'url': u'http://git01.base-fx.com:88/support/dvd',
                                   'clone': 'git clone http://git01.base-fx.com:88/support/dvd'}},
        'bfx':
            {
                u'bfx / bfx_extend_nuke':
                    {
                        'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke',
                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke'
                    },
                u'bfx / bfx_mozaic': {'url': u'http://git01.base-fx.com:88/bfx/bfx_mozaic',
                                      'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_mozaic'},
                u'bfx / bfx_path': {'url': u'http://git01.base-fx.com:88/bfx/bfx_path',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_path'},
                u'bfx / bfx_extend_katana': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_katana',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_katana'},
                u'bfx / bfx_td_lib': {'url': u'http://git01.base-fx.com:88/bfx/bfx_td_lib',
                                      'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_td_lib'},
                u'bfx / bfx_extend_nuke_TXZ': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_txz',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_txz'},
                u'bfx / bfx_mlp': {'url': u'http://git01.base-fx.com:88/bfx/bfx_mlp',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_mlp'},
                u'bfx / bfx_extend_otio': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_otio',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_otio'},
                u'bfx / bfx_wrap_silhouette': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_silhouette',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_silhouette'},
                u'bfx / bfx_mod': {'url': u'http://git01.base-fx.com:88/bfx/bfx_mod',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_mod'},
                u'bfx / bfx_extend_nuke_SZLS': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_szls',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_szls'},
                u'bfx / Bfx Publisher and Builder Modules': {
                    'url': u'http://git01.base-fx.com:88/bfx/bfx_pub_builder_modules',
                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pub_builder_modules'},
                u'bfx / bfx_extend_nuke_BRI': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_BRI',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_BRI'},
                u'bfx / bfx_DGNP': {'url': u'http://git01.base-fx.com:88/bfx/bfx_dgnp',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_dgnp'},
                u'bfx / bfx_pletools_site_2_deployer': {
                    'url': u'http://git01.base-fx.com:88/bfx/bfx_pletools_site_2_deployer',
                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pletools_site_2_deployer'},
                u'bfx / bfx_extend_nuke_FORD': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_ford',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_ford'},
                u'bfx / bfx_wrap_katana': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_katana',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_katana'},
                u'bfx / bam_api': {'url': u'http://git01.base-fx.com:88/bfx/bam_api',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_api'},
                u'bfx / bfx_extend_nuke_AHA': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_AHA',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_AHA'},
                u'bfx / bfx_extend_nuke_CJSN': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_CJSN',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_CJSN'},
                u'bfx / bfx_testpletools': {'url': u'http://git01.base-fx.com:88/bfx/bfx_testpletools',
                                            'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_testpletools'},
                u'bfx / bfx_extend_nuke_xGCC': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_xGCC',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_xGCC'},
                u'bfx / bfx_seat': {'url': u'http://git01.base-fx.com:88/bfx/bfx_seat',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_seat'},
                u'bfx / bfx_extend_nuke_FBB': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_FBB',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_FBB'},
                u'bfx / bfx_wrap_speedtree': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_speedtree',
                                              'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_speedtree'},
                u'bfx / bfx_extend_nuke_WDN': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_WDN',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_WDN'},
                u'bfx / bfx_rpcserver': {'url': u'http://git01.base-fx.com:88/bfx/bfx_rpcserver',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_rpcserver'},
                u'bfx / dockerfile': {'url': u'http://git01.base-fx.com:88/bfx/dockerfile',
                                      'clone': 'git clone http://git01.base-fx.com:88/bfx/dockerfile'},
                u'bfx / bfx_wrap_unity': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_unity',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_unity'},
                u'bfx / bfx_low': {'url': u'http://git01.base-fx.com:88/bfx/bfx_low',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_low'},
                u'bfx / bfx_extend_unity': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_unity',
                                            'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_unity'},
                u'bfx / bfx_element_publish': {'url': u'http://git01.base-fx.com:88/bfx/bfx_element_publish',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_element_publish'},
                u'bfx / bfx_wrap_usd': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_usd',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_usd'},
                u'bfx / bfx_wrangling': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrangling',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrangling'},
                u'bfx / bfx_extend_nuke_SKYF': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_SKYF',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_SKYF'},
                u'bfx / bfx_config': {'url': u'http://git01.base-fx.com:88/bfx/bfx_config',
                                      'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_config'},
                u'bfx / bfx_edl': {'url': u'http://git01.base-fx.com:88/bfx/bfx_edl',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_edl'},
                u'bfx / bfx_KatanaSubmit': {'url': u'http://git01.base-fx.com:88/bfx/bfx_KatanaSubmit',
                                            'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_KatanaSubmit'},
                u'bfx / bfx_extend_syntheyes': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_syntheyes',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_syntheyes'},
                u'bfx / bfx_wrap_drlib': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_drlib',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_drlib'},
                u'bfx / bfx_lookdev': {'url': u'http://git01.base-fx.com:88/bfx/bfx_lookdev',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_lookdev'},
                u'bfx / bfx_extend_nuke_HYS': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_HYS',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_HYS'},
                u'bfx / bfx_task': {'url': u'http://git01.base-fx.com:88/bfx/bfx_task',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_task'},
                u'bfx / bfx_extend_houdini': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_houdini',
                                              'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_houdini'},
                u'bfx / bfx_playblast': {'url': u'http://git01.base-fx.com:88/bfx/bfx_playblast',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_playblast'},
                u'bfx / bfx_layout': {'url': u'http://git01.base-fx.com:88/bfx/bfx_layout',
                                      'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_layout'},
                u'bfx / bfx_extend_toolchefs_atoms': {
                    'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_toolchefs_atoms',
                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_toolchefs_atoms'},
                u'bfx / bfx_extend_nuke_MRL': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_MRL',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_MRL'},
                u'bfx / bam_efx': {'url': u'http://git01.base-fx.com:88/bfx/bam_efx',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_efx'},
                u'bfx / bfx_wrap_unreal': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_unreal',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_unreal'},
                u'bfx / BAM GUI Library': {'url': u'http://git01.base-fx.com:88/bfx/bam_gui',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_gui'},
                u'bfx / bfx_efx': {'url': u'http://git01.base-fx.com:88/bfx/bfx_efx',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_efx'},
                u'bfx / bfx_extend_3de': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_3de',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_3de'},
                u'bfx / bfx_cfx': {'url': u'http://git01.base-fx.com:88/bfx/bfx_cfx',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_cfx'},
                u'bfx / bfx_zjgs': {'url': u'http://git01.base-fx.com:88/bfx/bfx_zjgs',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_zjgs'},
                u'bfx / bfx_extend_nuke_CWT': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_CWT',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_CWT'},
                u'bfx / bfx_crowd': {'url': u'http://git01.base-fx.com:88/bfx/bfx_crowd',
                                     'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_crowd'},
                u'bfx / bfx_surfacing': {'url': u'http://git01.base-fx.com:88/bfx/bfx_surfacing',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_surfacing'},
                u'bfx / bfx_efx_internal': {'url': u'http://git01.base-fx.com:88/bfx/bfx_efx_internal',
                                            'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_efx_internal'},
                u'bfx / bam_usd_extend_katana': {'url': u'http://git01.base-fx.com:88/bfx/bam_usd_extend_katana',
                                                 'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_usd_extend_katana'},
                u'bfx / bfx_wrap_houdini_engine': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_houdini_engine',
                                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_houdini_engine'},
                u'bfx / bfx_extend_nuke_ANBO': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_anbo',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_anbo'},
                u'bfx / bfx_wrap_mocha': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_mocha',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_mocha'},
                u'bfx / bfx gana': {'url': u'http://git01.base-fx.com:88/bfx/bfx_gana',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_gana'},
                u'bfx / bam_usd_extend_maya': {'url': u'http://git01.base-fx.com:88/bfx/bam_usd_extend_maya',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_usd_extend_maya'},
                u'bfx / bfx_showextend_maya': {'url': u'http://git01.base-fx.com:88/bfx/bfx_showextend_maya',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_showextend_maya'},
                u'bfx / bfx_api_service': {'url': u'http://git01.base-fx.com:88/bfx/bfx_api_service',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_api_service'},
                u'bfx / bfx_shotside': {'url': u'http://git01.base-fx.com:88/bfx/bfx_shotside',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_shotside'},
                u'bfx / bfx_extend_nuke_LMV': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_LMV',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_LMV'},
                u'bfx / bfx_vendor_tool': {'url': u'http://git01.base-fx.com:88/bfx/bfx_vendor_tool',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_vendor_tool'},
                u'bfx / bfx_plate_qc': {'url': u'http://git01.base-fx.com:88/bfx/bfx_plate_qc',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_plate_qc'},
                u'bfx / bfx_rigging': {'url': u'http://git01.base-fx.com:88/bfx/bfx_rigging',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_rigging'},
                u'bfx / bam_usd_render': {'url': u'http://git01.base-fx.com:88/bfx/bam_usd_render',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_usd_render'},
                u'bfx / bam_usd_extend_houdini': {'url': u'http://git01.base-fx.com:88/bfx/bam_usd_extend_houdini',
                                                  'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_usd_extend_houdini'},
                u'bfx / bfx_extend_maya_UE4': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_maya_ue4',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_maya_ue4'},
                u'bfx / bfx_preset_editor': {'url': u'http://git01.base-fx.com:88/bfx/bfx_preset_editor',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_preset_editor'},
                u'bfx / bfx_slcs': {'url': u'http://git01.base-fx.com:88/bfx/bfx_slcs',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_slcs'},
                u'bfx / bfx_motion_render': {'url': u'http://git01.base-fx.com:88/bfx/bfx_motion_render',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_motion_render'},
                u'bfx / bfx_spfx': {'url': u'http://git01.base-fx.com:88/bfx/bfx_spfx',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_spfx'},
                u'bfx / bam_usd_surfacing': {'url': u'http://git01.base-fx.com:88/bfx/bam_usd_surfacing',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_usd_surfacing'},
                u'bfx / bfx_extend_nuke_CWVB': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_CWVB',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_CWVB'},
                u'bfx / bfx_wrap_pixar_rm4h': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rm4h',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rm4h'},
                u'bfx / bfx_assetlib_publish': {'url': u'http://git01.base-fx.com:88/bfx/bfx_assetlib_publish',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_assetlib_publish'},
                u'bfx / BAM Publisher': {'url': u'http://git01.base-fx.com:88/bfx/bam_publisher',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_publisher'},
                u'bfx / bfx_resources': {'url': u'http://git01.base-fx.com:88/bfx/bfx_resources',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_resources'},
                u'bfx / bfx_farm': {'url': u'http://git01.base-fx.com:88/bfx/bfx_farm',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_farm'},
                u'bfx / bfx_extend_nuke_JQR': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_jqr',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_jqr'},
                u'bfx / bfx_extend_nuke_SIXU': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_SIXU',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_SIXU'},
                u'bfx / bfx_extend_maya_stable': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_maya_stable',
                                                  'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_maya_stable'},
                u'bfx / bfx_extend_nuke_jjs': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_jjs',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_jjs'},
                u'bfx / bfx_py3': {'url': u'http://git01.base-fx.com:88/bfx/bfx_py3',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_py3'},
                u'bfx / bfx_extend_mari': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_mari',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_mari'},
                u'bfx / bfx_wrap_ktoa': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_ktoa',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_ktoa'},
                u'bfx / bfx_backup': {'url': u'http://git01.base-fx.com:88/bfx/bfx_backup',
                                      'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_backup'},
                u'bfx / bfx_extend_nuke_TRIX': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_TRIX',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_TRIX'},
                u'bfx / bfx_prometheus_dist': {'url': u'http://git01.base-fx.com:88/bfx/bfx_prometheus_dist',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_prometheus_dist'},
                u'bfx / bfx_dcc_scene_check': {'url': u'http://git01.base-fx.com:88/bfx/bfx_dcc_scene_check',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_dcc_scene_check'},
                u'bfx / bfx_extend_nuke_LSM': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_lsm',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_lsm'},
                u'bfx / bfx_wrap_mari': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_mari',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_mari'},
                u'bfx / bfx_pletools_site_2': {'url': u'http://git01.base-fx.com:88/bfx/bfx_pletools_site_2',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pletools_site_2'},
                u'bfx / bfx_extend_drlib': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_drlib',
                                            'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_drlib'},
                u'bfx / bfx_extend_pixar_rmps': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_pixar_rmps',
                                                 'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_pixar_rmps'},
                u'bfx / bfx_wrap_nuke': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_nuke',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_nuke'},
                u'bfx / bfx_publish': {'url': u'http://git01.base-fx.com:88/bfx/bfx_publish',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_publish'},
                u'bfx / bfx_microservices': {'url': u'http://git01.base-fx.com:88/bfx/bfx_microservices',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_microservices'},
                u'bfx / bfx_real_path': {'url': u'http://git01.base-fx.com:88/bfx/bfx_real_path',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_real_path'},
                u'bfx / bfx_extend_nuke_ZJGS': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_zjgs',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_zjgs'},
                u'bfx / bfx_usd_plugin': {'url': u'http://git01.base-fx.com:88/bfx/bfx_usd_plugin',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_usd_plugin'},
                u'bfx / bfx_pmd_tools': {'url': u'http://git01.base-fx.com:88/bfx/bfx_pmd_tools',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pmd_tools'},
                u'bfx / bfx_extend_nuke_CJH': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_CJH',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_CJH'},
                u'bfx / bfx_wrap_pixar_rmsk': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rmsk',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rmsk'},
                u'bfx / bfx_extend_nuke_FRD2': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_frd2',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_frd2'},
                u'bfx / bfx_extend_nuke_SNOW': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_snow',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_snow'},
                u'bfx / bfx_wrap_fabricengine': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_fabricengine',
                                                 'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_fabricengine'},
                u'bfx / bfx_lighting': {'url': u'http://git01.base-fx.com:88/bfx/bfx_lighting',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_lighting'},
                u'bfx / bfx_redis_cache': {'url': u'http://git01.base-fx.com:88/bfx/bfx_redis_cache',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_redis_cache'},
                u'bfx / bfx_rig_vfx_internal': {'url': u'http://git01.base-fx.com:88/bfx/bfx_rig_vfx_internal',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_rig_vfx_internal'},
                u'bfx / BFX Publisher Builder Framework': {
                    'url': u'http://git01.base-fx.com:88/bfx/bfx_pub_builder_framework',
                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pub_builder_framework'},
                u'bfx / bfx_pletools_site_2_vue': {'url': u'http://git01.base-fx.com:88/bfx/bfx_pletools_site_2_vue',
                                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pletools_site_2_vue'},
                u'bfx / BFX GUI Library': {'url': u'http://git01.base-fx.com:88/bfx/bfx_gui',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_gui'},
                u'bfx / bfx_preview': {'url': u'http://git01.base-fx.com:88/bfx/bfx_preview',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_preview'},
                u'bfx / bfx_wrap_pixar_rm4m': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rm4m',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rm4m'},
                u'bfx / bfx_extend_nuke_TWE': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_TWE',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_TWE'},
                u'bfx / bfx_io_publish': {'url': u'http://git01.base-fx.com:88/bfx/bfx_io_publish',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_io_publish'},
                u'bfx / bfx_playblast2': {'url': u'http://git01.base-fx.com:88/bfx/bfx_playblast2',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_playblast2'},
                u'bfx / Code Doc Generator': {'url': u'http://git01.base-fx.com:88/bfx/bfx_doxypy',
                                              'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_doxypy'},
                u'bfx / bfx_extend_maya_SNTA': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_maya_snta',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_maya_snta'},
                u'bfx / bfx_kuaidi': {'url': u'http://git01.base-fx.com:88/bfx/bfx_kuaidi',
                                      'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_kuaidi'},
                u'bfx / bfx_extend_maya_snow': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_maya_snow',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_maya_snow'},
                u'bfx / bfx_wrap_syntheyes': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_syntheyes',
                                              'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_syntheyes'},
                u'bfx / bfx_robot': {'url': u'http://git01.base-fx.com:88/bfx/bfx_robot',
                                     'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_robot'},
                u'bfx / bfx_extend_cityengine': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_cityengine',
                                                 'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_cityengine'},
                u'bfx / bfx_btrn': {'url': u'http://git01.base-fx.com:88/bfx/bfx_btrn',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_btrn'},
                u'bfx / bfx_extend_nuke_YSJ': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_YSJ',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_YSJ'},
                u'bfx / bfx_prv_asset_library': {'url': u'http://git01.base-fx.com:88/bfx/bfx_prv_asset_library',
                                                 'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_prv_asset_library'},
                u'bfx / bfx_anbo': {'url': u'http://git01.base-fx.com:88/bfx/bfx_anbo',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_anbo'},
                u'bfx / bfx_example_video': {'url': u'http://git01.base-fx.com:88/bfx/bfx_example_video',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_example_video'},
                u'bfx / bfx_meta_view': {'url': u'http://git01.base-fx.com:88/bfx/bfx_meta_view',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_meta_view'},
                u'bfx / bfx_extend_nuke_N4D': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_N4D',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_N4D'},
                u'bfx / BFX Pipeline Engine': {'url': u'http://git01.base-fx.com:88/bfx/bfx_pipeline_engine',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pipeline_engine'},
                u'bfx / bfx_tx_publish': {'url': u'http://git01.base-fx.com:88/bfx/bfx_tx_publish',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_tx_publish'},
                u'bfx / bfx_extend_unreal': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_unreal',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_unreal'},
                u'bfx / bfx_extend_silhouette': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_silhouette',
                                                 'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_silhouette'},
                u'bfx / bfx': {'url': u'http://git01.base-fx.com:88/bfx/bfx',
                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx'},
                u'bfx / bfx_extend_nuke_AUD': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_aud',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_aud'},
                u'bfx / em_test': {'url': u'http://git01.base-fx.com:88/bfx/em_test',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/em_test'},
                u'bfx / bam_usd_api': {'url': u'http://git01.base-fx.com:88/bfx/bam_usd_api',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_usd_api'},
                u'bfx / bfx_rigging_internal': {'url': u'http://git01.base-fx.com:88/bfx/bfx_rigging_internal',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_rigging_internal'},
                u'bfx / bfx_nameconvention': {'url': u'http://git01.base-fx.com:88/bfx/bfx_nameconvention',
                                              'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_nameconvention'},
                u'bfx / bfx_wrap_pixar_rmps': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rmps',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rmps'},
                u'bfx / bfx_extend_nuke_HUCK': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_HUCK',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_HUCK'},
                u'bfx / bfx_plate_ingest': {'url': u'http://git01.base-fx.com:88/bfx/bfx_plate_ingest',
                                            'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_plate_ingest'},
                u'bfx / bfx_assetmgr': {'url': u'http://git01.base-fx.com:88/bfx/bfx_assetmgr',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_assetmgr'},
                u'bfx / bfx_extend_nuke_DPSH': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_dpsh',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_dpsh'},
                u'bfx / bfx_pathconvert': {'url': u'http://git01.base-fx.com:88/bfx/bfx_pathconvert',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pathconvert'},
                u'bfx / bfx_hdr_publish': {'url': u'http://git01.base-fx.com:88/bfx/bfx_hdr_publish',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_hdr_publish'},
                u'bfx / bfx_message': {'url': u'http://git01.base-fx.com:88/bfx/bfx_message',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_message'},
                u'bfx / bfx_api': {'url': u'http://git01.base-fx.com:88/bfx/bfx_api',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_api'},
                u'bfx / BAM Dev Tools': {'url': u'http://git01.base-fx.com:88/bfx/bam_dev_tools',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bam_dev_tools'},
                u'bfx / bfx_reference_publish': {'url': u'http://git01.base-fx.com:88/bfx/bfx_reference_publish',
                                                 'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_reference_publish'},
                u'bfx / bfx_database': {'url': u'http://git01.base-fx.com:88/bfx/bfx_database',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_database'},
                u'bfx / Unreal Plugins': {'url': u'http://git01.base-fx.com:88/bfx/unreal-plugins',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/unreal-plugins'},
                u'bfx / bfx_extend_nuke_FFXB': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_ffxb',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_ffxb'},
                u'bfx / bfx_convert': {'url': u'http://git01.base-fx.com:88/bfx/bfx_convert',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_convert'},
                u'bfx / bfx_orm': {'url': u'http://git01.base-fx.com:88/bfx/bfx_orm',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_orm'},
                u'bfx / bfx_extend_nuke_BUC': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_buc',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_buc'},
                u'bfx / bfx_extend_maya_ws20': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_maya_ws20',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_maya_ws20'},
                u'bfx / bfx_sweatbox': {'url': u'http://git01.base-fx.com:88/bfx/bfx_sweatbox',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_sweatbox'},
                u'bfx / bfx_wrap_pixar_rm4k': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rm4k',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_pixar_rm4k'},
                u'bfx / bfx_wrap_maya': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_maya',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_maya'},
                u'bfx / bfx_extend_nuke_SNMN': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_snmn',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_snmn'},
                u'bfx / bfx_outsource': {'url': u'http://git01.base-fx.com:88/bfx/bfx_outsource',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_outsource'},
                u'bfx / bfx_extend_maya': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_maya',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_maya'},
                u'bfx / bfx_wrap_yeti': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_yeti',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_yeti'},
                u'bfx / bfx_extend_nuke_xTST': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_xTST',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_xTST'},
                u'bfx / bfx_extend_ue4': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_ue4',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_ue4'},
                u'bfx / bfx_wrap_redshift_core': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_redshift_core',
                                                  'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_redshift_core'},
                u'bfx / bfx_wrap_pyqt': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_pyqt',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_pyqt'},
                u'bfx / bfx_extend_maya_WS2': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_maya_ws2',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_maya_ws2'},
                u'bfx / bfx_extend_nuke_ACP': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_acp',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_acp'},
                u'bfx / BFX Data': {'url': u'http://git01.base-fx.com:88/bfx/bfx_data',
                                    'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_data'},
                u'bfx / bfx_animation': {'url': u'http://git01.base-fx.com:88/bfx/bfx_animation',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_animation'},
                u'bfx / bfx_extend_clarisse': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_clarisse',
                                               'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_clarisse'},
                u'bfx / bfx_extend_rv': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_rv',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_rv'},
                u'bfx / bfx_taskstarter': {'url': u'http://git01.base-fx.com:88/bfx/bfx_taskstarter',
                                           'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_taskstarter'},
                u'bfx / bfx_extend_nuke_SNTA': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_snta',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_snta'},
                u'bfx / bfx_wrap_qt': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_qt',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_qt'},
                u'bfx / bfx_wrap_houdini': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_houdini',
                                            'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_houdini'},
                u'bfx / _scm_tools': {'url': u'http://git01.base-fx.com:88/bfx/bfx_scm',
                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_scm'},
                u'bfx / bfx_wrap_redshift_maya': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_redshift_maya',
                                                  'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_redshift_maya'},
                u'bfx / py_auto_cache': {'url': u'http://git01.base-fx.com:88/bfx/py_auto_cache',
                                         'clone': 'git clone http://git01.base-fx.com:88/bfx/py_auto_cache'},
                u'bfx / bfx_wrap_3de': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_3de',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_3de'},
                u'bfx / bfx_bluebird': {'url': u'http://git01.base-fx.com:88/bfx/bfx_bluebird',
                                        'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_bluebird'},
                u'bfx / bfx_wrap_rv': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_rv',
                                       'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_rv'},
                u'bfx / bfx_deploy': {'url': u'http://git01.base-fx.com:88/bfx/bfx_deploy',
                                      'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_deploy'},
                u'bfx / bfx_wrap_flowbox': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_flowbox',
                                            'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_flowbox'},
                u'bfx / bfx_wrap_nukex': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_nukex',
                                          'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_nukex'},
                u'bfx / bfx_extend_katana2_SKYF': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_katana2_SKYF',
                                                   'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_katana2_SKYF'},
                u'bfx / bfx_pletools_site': {'url': u'http://git01.base-fx.com:88/bfx/bfx_pletools_site',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_pletools_site'},
                u'bfx / bfx_extend_nuke_SPFX': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_spfx',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_spfx'},
                u'bfx / bfx_extend_nuke_WWND': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_WWND',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_WWND'},
                u'bfx / bfx_extend_nuke_HUC2': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_HUC2',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_HUC2'},
                u'bfx / bfx_wrap_clarisse': {'url': u'http://git01.base-fx.com:88/bfx/bfx_wrap_clarisse',
                                             'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_wrap_clarisse'},
                u'bfx / bfx_extend_nuke_ALNT': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_nuke_alnt',
                                                'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_nuke_alnt'},
                u'bfx / bfx_extend_katana2': {'url': u'http://git01.base-fx.com:88/bfx/bfx_extend_katana2',
                                              'clone': 'git clone http://git01.base-fx.com:88/bfx/bfx_extend_katana2'}}}

for grp in git_branches:
    projects = git_branches[grp]
    for project in projects:
        clone_cmd = projects[project]['clone']
        print clone_cmd
        bash_cmd = clone_cmd + '.git'
        os.chdir(r'D:\scripts\sandbox\gitlab_test\{}'.format(grp))
        p = subprocess.Popen(bash_cmd, stdout=subprocess.PIPE, stdin=subprocess.PIPE, shell=True)
        while p.poll() is None:
            stdout = p.stdout.readline().rstrip("\n")
            if stdout:
                print(stdout)
            buff = p.stdout.readline()
        p.communicate()
        status = p.returncode
        print(status)
